# -*- coding: utf-8 -*-
"""Dados Netflix

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zgXULxCsz8aS--d_2eCG4Qe4bAH6xdPP
"""

import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

pd.read_csv('netflix_movie.csv')

netflix = pd.read_csv('netflix_movie.csv')

netflix

netflix.describe().transpose()

netflix.shape

netflix["White Chicks"].value_counts()

netflix["PG-13"].value_counts()

netflix.info()

netflix.isnull().sum() #Detecção de valores nulos

#Detecção de valores discrepantes
netflix.plot(kind='box', subplots=True, layout=(8,5), figsize=(17,20))

col = netflix.columns

for i in range(len(col)):
    netflix.hist(column=[col[i]],bins=5, figsize=(6,3))